---
name: Test

on:
    pull_request:
        types:
            - closed

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                # Check out the commit hash of the PR branch, since the branch
                # itself may have already been deleted.
                ref: "${{ github.event.pull_request.head.sha }}"
            # Create a branch locally with the same name as the PR branch, so
            # operations that rely on the branch name will work as expected.
            - run: git switch --create "${{ github.event.pull_request.head.ref }}"
            - run: echo "$(git branch --show-current)"
